---
title: "AN/BI 333/733: Final Projects"
author: "Christopher A Schmitt"
date: "September 3, 2024"
output: 
  rmarkdown::html_document:
    theme: cosmo
---

***

### [Syllabus](https://fuzzyatelin.github.io/AN333_Fall24/Syllabus.html)
### [Modules](https://fuzzyatelin.github.io/AN333_Fall24/LabSyllabus.html)
### [Exam]()
### [Policies](https://fuzzyatelin.github.io/AN333_Fall24/policies.html)
### [Final Project](https://fuzzyatelin.github.io/AN333_Fall24/FinalProject.html)

***

## Final Projects for AN333/733

Your final project is a critically important part of this course. Once you’ve learned population genetic methods and how to use them on human *UCP1* data, it’s time to choose a candidate gene of your own to analyze!

Choose a gene that you can show is related to a trait that is integral to why you are interested in human population and evolutionary history. You will establish hypotheses, based on your knowledge of human population and evolutionary history, regarding how that gene should vary across the *1000 Genomes Project* dataset, and then test your hypotheses using the analytical methods learned in class.

We will choose loci together as part of [Module 7](https://fuzzyatelin.github.io/AN333_Fall24/Lab7-newlocus.html), but this guide is to help you through the process of preparing an writing your final paper.

<center>
## [**Please submit your Final Project paper as a single saved Google Doc file (downloaded as a Microsoft Word, or *.docx* file) at this link by 5:00pm of Thursday, December 19**](https://drive.google.com/drive/folders/0B-JPsQ7TL_bUflJveXdFTUVXaHgyeElCYmstYXlsME1xclhaZ280VW9BRm1VZnVKWldmbkE?resourcekey=0-GnTNRw3ClqpqFns6dQ-3GQ&usp=share_link)
</center>

## Final Project Paper Formatting

For this semester, we'll be submitting the final project as if it were a manuscript for publication in the open-access MDPI-published journal [*Genes*](https://www.mdpi.com/journal/genes). *Genes* is a convenient journal to submit to because they have a pre-established formatting template that we can use to prepare our submission, available to you [on Blackboard](https://learn.bu.edu/ultra/courses/_119228_1/outline/file/_14784464_1) in the Final Project folder.

All formatting requirements are available in the formatting document, which *must* be opened with Microsoft Word (Word is available for free for all BU students [here](https://www.bu.edu/tech/services/cccs/desktop/distribution/microsoft/studentoffice/)).

You may either work directly with the template itself, or work first in a Google Doc and then paste your text into the template. Should you opt for the former, the formatting guidelines below apply to the Google Doc - this will look very different in the *Genes* template (i.e., text will be more condensed, the paper will, overall, likely be shorter; that's ok!).

Some other details to keep in mind:

* Please list the *Type of Paper* as an *Article*
* For you affiliation, please list the **Department of *your major*, Boston University**. Mine is the *Department of Anthropology, Boston University*.
* You do *not* need to include anything in the section on Patents.
* Please *do* include appropriate information in the *Author Contributions* section.
* You should get IRB and Informed Consent information from the original 1000 Genomes Project publications we read for class.

Most importantly, *please include your code for your final project analyses as an Appendix*. I know this will potetnially be a lot of code, so the best way to include it may be as **a link to a Google Doc that contains all your final project code**.


### Guidelines for a Google Doc draft

The body of your paper should no less than 7 and no more than 10 pages long using 12-point font, double-spaced, with 1-inch margins (*not* including title/author lines, abstract, tables, figures, or references). For graduate students, this may be extended to 15 pages, but *no longer*.

1)  **Title and Author List**: Your title should be short and describe the central idea of your paper. See other titles published in *Genes* for some helpful examples. All projects should include yourself as first author and myself, as your instructor, as final author. Unless otherwise arranged, these should be the only two authors!

2)	**Abstract**: Please provide an abstract of 250 words or fewer containing the major keywords summarizing the article, structured with the following headings in bold, separated by line breaks: *Background/Objectives*, *Methods*, *Results*, *Conclusions*.

3)	**Introduction**: The *Introduction* should provide enough background for the reader to understand the objectives and motivation of the study. *Extensive literature review is unnecessary and should be avoided*, but please do include key readings that contextualize the project.

4)	**Materials and Methods**: This section should include all the information that would be necessary for a replication of the study as well as for a generally informed reader to evaluate the study and its results. Highly specialized procedures or forms of analysis may need explication so as to be understood by a generalist. A clear statement of approval by relevant ethics panels must be included for your dataset (see original publication of the *1000 Genomes Project* Consortium to find their ethics statement).

5)	**Results**: The *Results* section should present the findings of the study without excessive interpretation.

6)	**Discussion/Conclusions**: The *Discussion* section is the appropriate place for all interpretation of the study results, comparison with the results of previous studies, conclusions and hypotheses based on those comparisons, and suggestions for future research. No new analyses or results should appear in this section. Interpretations and conclusions should be restrained and justified by the results.

7)	**References**: For the *References section*, please follow the guidelines in the manuscript template.

8)  **Tables and Figures**: The best way to represent your data may be in a figure or table (for example, an image of the linkage blocks in your gene of interest, or of a neighbor-joining tree, or a table summarizing relavant neutrality statistics with their p-values). If you plan to include tables and figures, please number them in the order they appear in the text (Figure 1, Figure 2, etc; Table 1, Table 2, etc) with a descriptive caption describing/explaining what the table or figure is meant to show us that is relevant to your hypotheses (e.g., "Figure 1: Linkage block of the gene *ESPN3*, notice that there is high linkage between SNP of interest rs31459 and SNP rs44444, which is a candidate gene for obesity").

<ul><li>For guidance on how to include and caption a **figure**, see the template itself which has good guidance!</li>

<li>For guidance on how to add and edit a **table**, see the template!</li></ul>

9) Remember, you *must* submit your final project paper as a Word document using the template! So if you do make this in a Google Doc, please copy and paste all elements to the template and submit that as your final project paper!



<br>
<br>
<br>


