---
title: "AN/BI 588: Homework 02"
date: "August 18, 2023"
output:
  html_document:
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	comment = "##",
	prompt = TRUE,
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 75),
	fig.path = "img/"
)
```

***

### [Course Outline](https://fuzzyatelin.github.io/bioanth-stats/outline.html)
### [Course Overview](https://fuzzyatelin.github.io/bioanth-stats/overview.html)
### [Modules](https://fuzzyatelin.github.io/bioanth-stats/modules.html)
### [Assignments](https://fuzzyatelin.github.io/bioanth-stats/assignments.html)
### [Resources](https://fuzzyatelin.github.io/bioanth-stats/resources.html)
### [Policies](https://fuzzyatelin.github.io/bioanth-stats/policies.html)
### [Insurmountable Coding Problems](https://fuzzyatelin.github.io/bioanth-stats/studentproblems.html)

***

<center>
<font size="+2"><b>Titis in the Mist...</b></font></center><br>

<br><center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/CkUCCyhv5Xc?start=161&end=257&autoplay=1&loop=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen style="border:5px solid black"></iframe>
</center>
<br>

***

<center>

<font size="+2"><b>Must be submitted for Peer Commentary by 5:00 pm Friday, September 29th.</b></font>

</center><br>

<center>

<font size="+2"><b>Peer Commentary and Final Homework DUE at 5:00 pm Wednesday, October 04th.</b></font>

</center><br>

***

Every Saturday morning, at the same time, a primatologist goes and sits in the forest to listen for titi monkey calls, counting the number of calls they hear in a 2 hour window from 5am to 7am. Based on previous knowledge, she believes that the mean number of calls she will hear in that time is exactly 15. Let X represent the appropriate Poisson random variable of the number of calls heard in each monitoring session.

- What is the probability that she will hear more than 8 calls during any given session?
- What is the probability that she will hear no calls in a session?
- What is the probability that she will hear exactly 3 calls in a session?
- Plot the relevant Poisson mass function over the values in range 0 ≤ x ≤ 30.
- Simulate 104 results from this distribution (i.e., 2 years of Saturday monitoring sessions).
- Plot the simulated results using hist() and use xlim() to set the horizontal limits to be from 0 to 30. How does your histogram compare to the shape of the probability mass function you plotted above?

***

### **Your Final Assignment for Homework 02**

Your final assignment, due to me by 5:00 pm on October 04th, is to have in your *AN588-Week-3-BUlogin* repo only the following six (6) files (aside from repo basics like an `.Rproj` and `README` file):
<ol>
1. The *FINAL PUSH* of your Original Homework Code, including the five challenges you faced, as pushed to your repo by 5:00 pm on Friday September 29th, an R Markdown *and* HTML file named *BUlogin_OriginalHomeworkCode_02*.
2. The *FINAL PUSH* of the [Peer Commentary](https://fuzzyatelin.github.io/bioanth-stats/peercommentary.html) made on *your* code, an R Markdown *and* HTML file named *Peerlogin_PeerCommentary_BUlogin_02* or *PeerGroupX_PeerCommentary_BUlogin_02*.
3. The *FINAL PUSH* of your Final Homework Code, which has taken into account any changes recommended from the Peer Commentary and notes, an R Markdown *and* HTML file named *BUlogin_FinalHomeworkCode_02*.
</ol>

**Formatting Instructions**: Please use the `cayman` theme (from the {prettydoc} package) in your Final Homework Code, with a `Header 2` title for each question you answer. These headers should be organized in a Table of Contents. Add to the top of the document, under your title, your favorite picture or video of a titi monkey that you're able to find online.

***

### [Homework 02 Solutions](https://fuzzyatelin.github.io/bioanth-stats/homework-02-key.html) will be posted on October 5th.

***

NOTE: If you want your homework code to look nice (beyond being *very* well annotated and commented), and be easy to use by others, you can check out the relatively simply example **R Markdown** templates in the [AN588_Week_3_caschmit](https://github.com/fuzzyatelin/AN588_Week_3_caschmit) repo.

Please also consider consulting the following helpful guidelines on how to write effective **R Markdown** documents (also available at the end of [Module 03](https://fuzzyatelin.github.io/bioanth-stats/module-03/module-03.html)), which go well beyond the simple formatting of the templates.
<ul>
<li>An introduction to [R Markdown](https://rmarkdown.rstudio.com/)</li>
<li>[R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)</li>
<li>[R Markdown Cheatsheet](https://rmarkdown.rstudio.com/lesson-15.html)</li>
<li>[Another R Markdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)</li>
<li>[Pimp my RMD: A Few Tips for R Markdown](https://holtzy.github.io/Pimp-my-rmd/)</li>
<li>[R Markdown Templates for Journal Submissions](https://github.com/rstudio/rticles/tree/master/inst/rmarkdown/templates)</li>
<li>[Using R Markdown for Class Reports](https://www.stat.cmu.edu/~cshalizi/rmarkdown/)</li>
<li>[R Markdown Theme Gallery](http://www.datadreaming.org/post/r-markdown-theme-gallery/)</li>
<li>[Creating Pretty Documents from R Markdown](https://cran.r-project.org/web/packages/prettydoc/vignettes/architect.html)</li>
</ul>
<br>