---
title: "Useful Data Science Resources"
output: html_document
---

###[Course Overview](https://fuzzyatelin.github.io/bioanth-stats/overview.html)
###[Course Outline](https://fuzzyatelin.github.io/bioanth-stats/outline.html)
###[Modules](https://fuzzyatelin.github.io/bioanth-stats/modules.html)
###[Policies](https://fuzzyatelin.github.io/bioanth-stats/policies.html)
###[Coding Problems](https://fuzzyatelin.github.io/bioanth-stats/studentproblems.html)
***

###Software Tools
***

####Programming Languages
<ul>
<li>[R](https://cran.r-project.org) (MacOS, Windows, Linux)</li>
<li>[Python](http://www.python.org) (MacOS, Windows, Linux)</li>
</ul>

####Text Editors
<ul>
<li>[Atom](https://atom.io) (MacOS, Windows)</li>
<li>[TextWrangler](http://www.barebones.com/products/textwrangler/download.html) (MacOS)</li>
<li>[nvAlt](http://brettterpstra.com/projects/nvalt/) (MacOS)</li>
<li>[Notepad++](https://notepad-plus-plus.org/) (Windows)</li>
<li>[Vim](https://vim.sourceforge.io) (MacOS, Windows)</li>
</ul>

####Markdown Editors
<ul>
<li>[MacDown](http://macdown.uranusjr.com/) (MacOS)</li>
<li>[MarkdownPad2](http://markdownpad.com/) (Windows)</li>
</ul>

####IDEs
<ul>
<li>[RStudio](https://www.rstudio.com/) for **R** (current version is 1.0.136) (MacOS, Windows)</li>
<li>[y-hat Rodeo](https://www.yhat.com/products/rodeo) for **Python** (current version is 2.4.10) (MacOS, Windows, Linux)</li>
</ul>

####Version Control Tools
<ul>
<li>[GitHub](https://github.com/) (Website)</li>
<li>[GitHub Desktop](https://desktop.github.com/) (MacOS, Windows)</li>
</ul>

###Web Resources
***
<ul>
<li>[CRAN (Comprehensive R Archive Network)](https://cran.r-project.org/)</li>
<li>[DataCamp](https://www.datacamp.com/)</li>
<li>[Software Carpentry](http://software-carpentry.org/)</li>
<li>[Data Carpentry](http://www.datacarpentry.org/)</li>
<li>[rOpenSci](https://ropensci.org/)</li>
<li>[Stack Overflow](http://stackoverflow.com/)</li>
<li>[Stack Exchange](http://stackexchange.com)</li>
<li>[Online R Exercises](http://r-exercises.com/start-here-to-learn-r/)</li>
<li>[R-bloggers](https://www.r-bloggers.com/)</li>
<li>[Mockaroo](https://mockaroo.com/)</li>
</ul>

###Books
***

####Statistical Modeling in Biology
<ul>
<li>Bolker BM. 2008. *Ecological Models and Data in R*. Princeton, NJ: Princeton University Press.</li>
<li>Irizarry RA, Love MI. 2015. *Data Analysis for the Life Sciences*. Lean Publishing.</li>
<li>Quinn GP, Keough MJ. 2002. *Experimental Design and Data Analysis for Biologists*. Cambridge, UK: Cambridge University Press.</li>
</ul>

####R and Basic Statistics
<ul>
<li>Caffo B. 2015. *Statistical Inference for Data Science*. Lean Publishing.</li>
<li>Caffo B. 2016. *Regression Models for Data Science in R*. Lean Publishing.</li>
<li>Dalgaard P. 2008. *Introductory Statistics with R (Second Edition)*. New York: Springer.</li>
<li>Shahbaba B. 2012. *Biostatistics with R*. New York: Springer.</li>
</ul>

####R Programming
<ul>
<li>Adler J. 2009. *R in a Nutshell*. Sebastopol, CA: O’Reilly Media.</li>
<li>Kabacoff RI. 2011. *R in Action: Data Analysis and Graphics with R*. Shelter Island, NY: Manning Publications Co.</li>
<li>Matloff N. 2011. *The Art of R Programming: A Tour of Statistical Software Design*. San Francisco: No Starch Press.</li>
<li>Peng R. 2016. *R Programming for Data Science*. Lean Publishing.</li>
<li>Peng R. 2016. *Exploratory Data Analysis with R*. Lean Publishing.</li>
<li>Zuur AF, Ieno EN, Meesters EHWG. 2009. *A Beginner’s Guide to R*. New York: Springer.</li>
</ul>

####R Reference
<ul>
<li>Crawley MJ. 2012. *The R Book (Second Edition)*. Chichester, UK: John Wiley & Sons Ltd.</li>
<li>Gardener M. 2012. *The Essential R Reference*. Indianapolis, IN: John Wiley & Sons, Inc.</li>
<li>Teetor P. 2011. *R Cookbook*. Sebastopol, CA: O’Reilly Media.</li>
</ul>

####R Graphics
<ul>
<li>Chang W. 2013. *R Graphics Cookbook*. Sebastopol, CA: O’Reilly Media.</li>
<li>Wickham H. 2016. *ggplot2: Elegant Graphics for Data Analysis (Second Edition)*. Springer International Publishing.</li>
</ul>

####Data Science and Visualization
<ul>
<li>Dale K. 2016. *Data Visualization with Python and JavaScript*. Sebastopol, CA: O’Reilly Media.</li>
<li>Grus J. 2015. *Data Science from Scratch*. Sebastopol, CA: O’Reilly.</li>
<li>Kazil J, Jarmul K. 2016. *Data Wrangling with Python*. Sebastopol, CA: O’Reilly.</li>
<li>Peng RD, Matsui E. 2015. *The Art of Data Science*. Lean Publishing.</li>
<li>Zumel N, Mount J. 2014. *Practical Data Science with R*. Shelter Island, NY: Manning Publications Co.</li>
</ul>

####Spatial Analysis
<ul>
<li>Bivand RS, Pebesma E, Gómez-Rubio V. 2013. *Applied Spatial Data Analysis with R (Second Edition)*. New York: Springer.</li>
<li>Brundson C, Comber L. 2015. *An Introduction to R for Spatial Analysis and Mapping*. London: SAGE Publications, Ltd.</li>
</ul>

####Mixed Effects Models
<ul>
<li>Garamszegi LZ. 2014. *Modern Phylogenetic Comparative Methods and Their Application in Evolutionary Biology*. Berlin: Springer.</li>
<li>Pinheiro JC, Bates DM. 2000. *Mixed-Effects Models in S and S-Plus*. New York: Springer.</li> 
<li>Zuur AF, Ieno EN, Walker NJ, Savaliev AA, Smith GM. 2009. *Mixed Effects Models and Extensions in Ecology with R*. New York: Springer.</li>
</ul>

####Web Scraping and Text Mining
<ul>
<li>Friedl JEF. 2000. Mastering Regular Expressions (Third Edition). Sebastopol, CA: O’Reilly Media.</li>
<li>Mitchell R. 2015. Web Scraping with Python. Sebastopol, CA: O’Reilly Media.</li>
<li>Nolan D, Temple Lang D. 2014. XML and Web Technologies for Data Sciences with R. New York: Springer.</li>
</ul>

####Statistics and Programming in Python
<ul>
<li>Downey A. 2014. Think Stats (Second Edition). Sebastopol, CA: O’Reilly Media.</li>
<li>Lubanovic B. 2014. Introducing Python. Sebastopol, CA: O’Reilly Media.</li>
<li>McKinney W. 2013. Python for Data Analysis. Sebastopol, CA: O’Reilly.</li>
</ul><br><br>