---
title: 'AN 902: SMAGL Anthropological Genetics Internship Outline'
author: "Christopher A Schmitt"
date: "February 18, 2024"
output: 
  rmdformats::readthedown:
    toc_depth: 5
---

***

### **Week 01 (January 22, 2024)**
***

#### An Introduction to the SMAGL Internship

##### Topics for Discussion

We'll discuss general expectations for the course, required trainings and approvals for lab access, and the projects we'll be working on throughout the semester.

##### Lab Practicum

**SMAGL Wet Lab Orientation**: we will walk through the [SMAGL Wet Lab](https://www.bu.edu/anthrop/research/laboratories/sensory-morphology-and-genomic-anthropology-lab-smgal/) and go over the basics of the space, including basic lab safety and etiquette, assign and discuss PPE, and go over what is and is not accessible to you while conducting this internship.

##### SMAGL Lab Meeting

**Introductory Lab Meeting**: we will meet the other members of the SMAGL at our first lab meeting of the semester! Please come prepared to share your goals for the semester, and to set your goals for the coming week.

##### Required Readings

**Mandatory Lab Trainings**: you have already been added to the SMAGL Schmitt Lab on [BioRAFT](https://www.bu.edu/ehs/ehs-topics/about-bioraft/), and have several associated trainigs that are **required** for you to complete **prior to** entering the wet bench space in STO 251. **Please complete these before Monday, January 22!**

***

### **Week 02 (January 29, 2024)**
***

#### Introduction to Molecular Genetics

##### Topics for Discussion

We'll discuss the basics of molecular genetics - what is DNA and RNA, what is a gene and how does it work, and a brief history of molecular genetics techniques.

##### Lab Practicum

It's time to pipette!  We'll learn some *very* basic lab skills in the wet lab today, including how to clean up a work bench, how to run the BSC, how to run the UV hoods, and how to run the autoclave.

##### SMAGL Lab Meeting

Schmitt Lab first-year Ph.D. student Jimmy Erkens will be introducing us to the green monkeys (*Chlorocebus sabaeus*) of St. Kitts & Nevis this week!

##### Background Readings

Strachan & Read: Chapter 1 (Basics Principles of Nucleic Acid Structure and Gene Expression)

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + [Brun et al. 2022. Focal vs. fecal: Seasonal variation in the diet of wild vervet monkeys from observational and DNA metabarcoding data. *Ecology and Evolution* 12(10): e9358.](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.9358)
* **Fecal Microbiome Project**
    + [Clayton et al. 2018. The gut microbiome of nonhuman primates: Lessons in ecology and evolution. *American Journal of Primatology* 80(6): e22867.](https://onlinelibrary.wiley.com/doi/full/10.1002/ajp.22867?casa_token=61srKkUnibUAAAAA%3AJrgQG0lxYGL0erEYALWcbZ9K-BjRpCiSEZ4B-M_S1_SBleLJfirfLtNcsXxQnlh4C6C5uzFoKFVZtw)


***

### **Week 03 (February 5, 2024)**
***

#### The Basics of Doing Genetics

##### Topics for Discussion

We'll discuss an overview of the basics of genetics lab work - from extraction to sequencing, with a focus on some key methodological considerations for the generation of DNA sequences critical for analyses relevant to the projects we plan on doing this semester.

##### Lab Practicum

This week in lab, we'll go over the basics of where things are in the lab that we'll use in our projects this semester, and why. We'll look briefly at relevant protocols, and identify and discuss potential issues with workflow in the lab before, in the coming weeks, diving into actual labwork!

##### SMAGL Lab Meeting

Schmitt Lab second-year Ph.D. student Jess Martin will walk us through her replication attempt of some previous (Illumina-based) vervet gut/fecal microbiome analyses using the R package {dada2} in a sample of wild vervet monkeys (*Chlorocebus pygerythrus*) in South Africa!

##### Background Readings

Strachan & Read: Chapter 6 (Core DNA Technologies: Amplifying DNA, Nucleic Acid Hybridization, and DNA Sequencing)

Jobling: Chapter 4 (Finding and Assaying Genome Diversity)

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + [Mallott et al. 2018. *trnL* outperforms *rbcL* as a DNA metabarcoding marker when compared with the observed plant component of the diet of wild white-faced capuchins (*Cebus capucinus*, Primates). *PLoS ONE* 13(6): e0199556](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199556)
    + [Pinto et al. 2023. Promise and limitations of 18S genetic screening of extracted fecal DNA from wild capuchins. *Frontiers in Ecology and Evolution* 11: fevo.2023.1176681](https://www.frontiersin.org/articles/10.3389/fevo.2023.1176681/full)
* **Fecal Microbiome Project**
    + [Song et al. 2016. Preservation Methods Differ in Fecal Microbiome Stability, Affecting Suitability for Field Studies. *mSystems* 1(3): 10.1128/msystems.00021-16](https://journals.asm.org/doi/full/10.1128/msystems.00021-16)
    + [Hayakawa et al. 2018. Improving the standards for gut microbiome analysis of fecal samples: insights from the field biology of Japanese macaques on Yakushima Island. *Primates* 59: 423–436](https://link.springer.com/article/10.1007/s10329-018-0671-x)

***

### **Week 04 (February 12, 2024)**
***

#### Cancelled due to illness.

***

### **Week 05 (February 21, 2024; WEDNESDAY)**
***

#### Extracting DNA from Feces (or Whatever)

##### Topics for Discussion

We'll discuss poop and what we can get from it. Along the way, we'll also dig in to other sample types and what they might be good for.

##### Lab Practicum

Please review the [SMAGL Microbiome Extractions: DNeasy PowerLyzer PowerSoil Kit 18FEB24](https://docs.google.com/document/d/10Pe05ih58cTuLuiQI-9DQE4XmkOcX_zY1uR5cgMGRZE/edit#heading=h.mlr9l8hl37ip) (request access if this is not accessible to you). Please copy this protocol to you lab notebook for the internship and make modifications to it there (NOT to the original document!).

We will walk through the protocol in lab this week in preparation for your performing extractions this week!

##### SMAGL Lab Meeting

**No lab meeting this week due to scheduling shift**

##### Background Readings

Strachan & Reed: Chapter 9 (Uncovering the Architecture and Workings of the Human Genome)

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + [Ando et al. 2020. Methodological trends and perspectives of animal dietary studies by noninvasive fecal DNA metabarcoding. *Environmental DNA* 2(4): 391-406.](https://onlinelibrary.wiley.com/doi/full/10.1002/edn3.117)
    + [McInnes et al. 2016. Optimised scat collection protocols for dietary DNA metabarcoding in vertebrates. *Methods in Ecology and Evolution* 8(2): 192-202.](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12677)
* **Fecal Microbiome Project**
    + [Videnska et al. 2019. Stool sampling and DNA isolation kits affect DNA quality and bacterial composition following 16S rRNA gene sequencing using MiSeq Illumina platform. *Scientific Reports* 9: 13837.](https://www.nature.com/articles/s41598-019-49520-3)
    + [Elie et al. 2023. Comparison of DNA extraction methods for 16S rRNA gene sequencing in the analysis of the human gut microbiome. *Scientific Reports* 13: 10279](https://www.nature.com/articles/s41598-023-33959-6)

***

### **Week 06 (February 26, 2024)**
***

#### Quantitating Genetic Material

##### Topics for Discussion

We'll talk about how we actually quantify how much genetic material is in a sample, and why that's important. We'll also talk about sample contamination, how we detect it, troubleshoot it, and get rid of it. 

##### Lab Practicum

We'll walk through the Quantitation Station today, and run an example sample through the dsDNA protocol on the Quantus and the NanoDrop. You'll be responsible for quantitating your extractions this week!

##### SMAGL Lab Meeting

Schmitt Lab fourth-year Ph.D. student and NSF Graduate Research Fellow Mel Zarate will discuss her NSF INTERN-funded work at the Broad Institute as part of her work with the Zoo New England Conservation Genomics Lab.

##### Background Readings

Strachan & Reed: Chapter 7 (Analyzing the Structure and Expression of Genes and Genomes)

##### Project-Specific Readings

* **Fecal Metabarcoding Project** & **Fecal Microbiome Project**
    + [Sedlackova et al. 2013. Fragmentation of DNA affects the accuracy of the DNA quantitation by the commonly used methods. *Biological Procedures Online* 15:5.](https://link.springer.com/article/10.1186/1480-9222-15-5)
    + [Nakayama et al. 2016. Pitfalls of DNA Quantification Using DNA-Binding Fluorescent Dyes and Suggested Solutions. *PLoS ONE* 11(3): e0150528](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0150528) 
* **Fecal Metabarcoding Project**
    + [Matthews et al. 2020. A comparison of fecal sampling and direct feeding observations for quantifying the diet of a frugivorous primate. (Current Zoology 66(4):333-343.)](https://academic.oup.com/cz/article/66/4/333/5643760)
* **Fecal Microbiome Project**
    + [Clayton et al. 2018. Associations Between Nutrition, Gut Microbiome, and Health in A Novel Nonhuman Primate Model. *Scientific Reports* 8:11159.](https://www.nature.com/articles/s41598-018-29277-x)
    
***

### **Week 07 (March 4, 2024)**
***

#### TBA

##### Topics for Discussion

##### Lab Practicum

##### SMAGL Lab Meeting

Lab meeting this week will entail practice presentations by lab members giving podium or poster presentations at the annual meeting of the American Association of Biological Anthropologists (AABA) in Los Angeles. Presenters include Dr. Evelyn Pain, Mel Zarate, Jimmy Erkens, and Sofia Weaver.

##### Background Readings

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + TBA
* **Fecal Microbiome Project**
    + TBA

***

### **Week 08 (March 11, 2024)**
***

#### **SPRING RECESS: NO FORMAL MEETINGS**

***

### **Week 09 (March 18, 2024)**
***

**NOTE: Annual Meeting fo the AABA is this week!** We will have Monday meetings, but Prof. Schmitt will be in Los Angeles for the rest of the week and unable to assist in lab.

#### TBA

##### Topics for Discussion

##### Lab Practicum

##### SMAGL Lab Meeting

Garrett Lab undergraduate Biology major Luke Buza will present his Honors Thesis, currently being conducted under the advisement of Dr. James Traniello in the Department of Biology.

##### Background Readings

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + TBA
* **Fecal Microbiome Project**
    + TBA

***

### **Week 10 (March 25, 2024)**
***

#### TBA

##### Topics for Discussion

##### Lab Practicum

##### SMAGL Lab Meeting

Schmitt Lab undergraduate Biology major, UROP student, and research-for-credit student Sofia Weaver will present on her prospective summer research project studying the Y chromosome of wild yellow-tailed woolly monkeys at the Wildlife Conservation Lab at Los Amigos in Perú.

##### Background Readings

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + TBA
* **Fecal Microbiome Project**
    + TBA

***

### **Week 11 (April 1, 2024)**
***

#### Sequencing using the ONT MinION

##### Topics for Discussion

We'll discuss what MinION sequencing is, how it works, and the benefits and drawbacks of this particular sequencing platform.

##### Lab Practicum

We'll work together to finish library preparation and be present while Mel Zarate walks us through our course sequencing reaction on the MinION Mk1B!

##### SMAGL Lab Meeting

Schmitt Lab undergraduate Anthropology major and research-for-credit student Reese Hotten-Somers will present on her prospective summer project studying whether the fecal microbiome of wild vervet monkeys can be used to assess SIV infection status.

##### Background Readings


##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + TBA
* **Fecal Microbiome Project**
    + TBA

***

### **Week 13 (April 8, 2024)**
***

#### TBA

##### Topics for Discussion

##### Lab Practicum

##### SMAGL Lab Meeting

TBA

##### Background Readings

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + TBA
* **Fecal Microbiome Project**
    + TBA

***

### **Week 14 (April 15, 2024)**
***

#### **PATRIOT'S DAY: NO FORMAL MEETINGS**

***

### **Week 15 (April 22, 2024)**
***

#### TBA

##### Topics for Discussion

##### Lab Practicum

##### SMAGL Lab Meeting

**Fecal Microbiome Project** will present their research results in the SMAGL Lab Meeting (CILSE 106C)

##### Background Readings

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + TBA
* **Fecal Microbiome Project**
    + TBA

***

### **Week 15 (April 29, 2024)**
***

#### TBA

##### Topics for Discussion

##### Lab Practicum

##### SMAGL Lab Meeting

**Fecal Metabarcoding Project** will present their research results in the SMAGL Lab Meeting (CILSE 106C)

##### Background Readings

##### Project-Specific Readings

* **Fecal Metabarcoding Project**
    + TBA
* **Fecal Microbiome Project**
    + TBA

***

### [Back to SMAGL Overview](https://fuzzyatelin.github.io/anthgen-intern/overview.html)

***