---
title: "SMAGL Contract and Code of Conduct"
author: "Christopher A Schmitt</br>Boston University"
date: "Feburary 4, 2025"
output: 
  rmdformats::readthedown:
    toc_depth: 5
---

This contract and code of conduct must be discussed and counter-signed with your PI at the beginning of every academic year that you are affiliated with the Schmitt Lab and SMAGL more broadly. The goal of this Code of Conduct is to ensure that the Principles supported by the Schmitt Lab/SMAGL are followed so that we may provide a safe and respectful environment for all members to thrive in while conducting research. This includes staff, faculty, researchers, students, contractors, technicians, visiting classes or students, interns, guests, and volunteers.

# Principles of Schmitt Lab/SMAGL

*	Excellence, integrity, and honesty in all aspects of professional/scientific work.
*	Professional courtesy, equity, and fairness in working with others.
*	Freedom to responsibly pursue science without interference or coercion.
*	Unselfish cooperation in all SMAGL activities.
*	Legal compliance in all aspects of the SMAGL’s professional activities.

# Responsibilities of Lab Members

*	Students will behave in a professional and courteous manner at all times while conducting research in the lab or while representing the lab on campus, at conferences, or in the field. 
*	Each student is expected to conduct him/herself in a spirit of cooperation, respect and thoughtfulness for other students, staff, and faculty in Schmitt Lab/SMAGL. 
*	Students will take responsibility for the integrity of their contributions to all professional activities related to Schmitt Lab/SMAGL and BU.
*	Students will acknowledge the names and roles of those who made significant contributions (such as ideas and scientific discussion) to Schmitt Lab/SMAGL activities. 
*	Students, when representing Schmitt Lab/SMAGL research in professional settings, will limit comments to their areas of expertise when engaged in public discussions about the research, and will clearly distinguish professional comments from their opinions based on personal views. 
*	Students will take responsibility to act or intercede where possible to prevent misconduct, and will report any suspected misconduct, including fabrication, falsification, or plagiarism of materials to PIs. *	Students will not use alcohol or illegal drugs (or be under the influence) while working in the SMAGL lab space or while actively conducting field research.
*	Students will abide by all rules and regulations of the lab or field site as set forth by PIs and PRAs.
*	All students that are part of the lab will attend the Schmitt Lab/SMAGL Lab Meetings unless otherwise engaged in coursework or paid employment.
*	Any transgression from professional conduct will result in a warning, and, if another similar transgression occurs, may be grounds for expulsion from the lab.

# Grounds for Expulsion

The Schmitt Lab/SMAGL is committed to creating a safe, diverse, inclusive, and equitable work and learning environment free from discrimination, harassment, bullying, microaggressions, or sexual misconduct. Any of these behaviors are grounds for expulsion from the lab. See below for definitions and potential outcomes of these behaviors.

## Discrimination

Discrimination means unequal or unfair treatment in professional opportunities, education, benefits, evaluation, and employment (such as hiring, termination, promotion, compensation) as well as retaliation and various types of harassment. Discriminatory practices can be explicit or implicit, intentional or unintentional. Discrimination on the basis of race, color, ethnicity, religion, sex, national origin, age, ancestry, disability, veteran status, sexual orientation, marital status, parental status, gender identify, gender expression and genetic information is prohibited under federal statutes, state statutes, and the BU Equal Opportunity/Affirmative Action Policy.

## Harassment

Harassment is a type of discrimination that involves actions, words or physical gestures that could reasonably be perceived to be the cause of another person’s distress or discomfort, or which put the safety of the individual at risk. This includes all behaviors that are unwanted by the recipient, which have the purpose or effect of violating the recipient’s dignity, marginalizing an individual either personally or professionally, or which create an intimidating, hostile, degrading, humiliating or offensive environment. It applies not only to direct interactions, but also other forms of communication including social media. These acts may include epithets, slurs, or negative stereotyping based on gender, race, sexual identity, or other categories, as protected by U.S. federal and MA state law. Also included are threatening, intimidating, or hostile acts; stalking; denigrating jokes and displays; or circulation of written or graphic material that denigrates or shows hostility or aversion toward an individual or a group. It becomes unlawful where enduring it becomes a condition of continued employment or when the conduct is severe or pervasive enough that a reasonable person would consider the work environment to be hostile.

## Bullying

Bullying is the repeated use of force, threat, or coercion to abuse, intimidate, or purposefully dominate others in the professional environment based on a real or perceived power imbalance. These actions can include abusive criticism, humiliation, the spreading of rumors, physical and verbal attacks, isolation, undermining, and professional exclusion of individuals through any means. Bullying will not be tolerated in the SMAGL.

## Microaggressions

Microaggressions are the everyday verbal, nonverbal, and environmental slights, snubs, or insults which communicate hostile, derogatory, or negative messages to target persons based solely upon their group membership. These messages may invalidate the group identity or experiential reality of targets, marginalize or demean them on a personal or group level, communicate they are lesser human beings, suggest they do not belong, threaten and intimidate, or relegate them to inferior status and treatment. Micro-aggressions are less overt and are often related to discrimination, harassment or bullying, but may also occur in well-intentioned individuals who are unaware that they have engaged in an offensive act or made an offensive statement. Microaggressions will not be tolerated in the SMAGL.

## Sexual Misconduct

Everyone in the SMAGL has the right to be free from discrimination, unlawful harassment, sexual misconduct, and violence. Title IX is a federal law that gives everyone the right to equal access to education and employment in the absence of sexual harassment and gender discrimination. During your time at the SMAGL you are expected to follow the law, as well as specific guidelines laid out in this Code of Conduct. Anyone working in the SMAGL is expected to conduct themselves in a manner that does not infringe on the rights of others. Violations will result in expulsion from the lab and repercussions at the college and university level.

### Unacceptable behaviors falling under sexual misconduct

The following behaviors are considered violations of the Schmitt Lab/SMAGL Code of Conduct:

*	Sexual Harassment includes unwelcome sexual advances, requests for sexual favors, other verbal or physical conduct of a sexual nature, and offensive comments related to gender, gender identity and expression, sexual orientation, physical appearance, and body size. 
*	Sexual Misconduct includes rape, sexual assault, inappropriate touching, sexual battery, sexual exploitation, coercion, and other forms of non-consensual sexual activity. 
*	Stalking is repeatedly following, harassing, threatening, or intimidating including by telephone, mail, electronic communication, or social media. 
*	Patterns of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others. 
*	Dating and Domestic Violence includes emotional, verbal, and economic abuse with or without the presence of physical abuse. 
*	Retaliation is adverse employment, academic or other actions against anyone reporting a violation of this policy (including reporting to any BU staff, management team member, police, or Title IX office). 
*	Title IX Violation is the collective term used for incidents involving discrimination, harassment, sexual harassment, sexual misconduct, stalking, dating violence, domestic violence, and/or retaliation. 
*	Power-based personal violence occurs when an individual asserts power, control, or intimidation in order to harm another. This includes relationship/partner violence, sexual assault, and stalking. 
*	Deliberately mis-characterizing a person's gender identity, including through the use of a name or pronoun that the person has rejected. 
*	Gratuitous or off-topic sexual images or behavior in spaces where they’re not appropriate in the lab or the field. 
*	Violating the Ask Once policy (defined below)

### Ask Once guideline

It is generally appropriate to ask someone out once, but no more than once. The Schmitt Lab/SMAGL follows Ask Once as a behavioral guideline. The Ask Once guideline means that you can ask someone out once, and if they do not say yes, you cannot ask them out again. Asking out includes hitting on, expressing interest, and making advances. If someone brushes off the advance, does not reciprocate in a positive way, or turns down the advance in any way, it must still be considered a “no”. This guideline is intended to inform the behavior of someone interested in another SMAGL lab member, give people a simple way to judge when they are being harassed, and give SMAGL PIs a tool in which to evaluate lab members’ behavior.

### Reporting options

**University Title IX Coordinator**
Jean Estevez, Executive Director of Equal Opportunity
Phone: (617) 358-1796
Email: titleix[at]bu[dot]edu
http://www.bu.edu/safety/sexual-misconduct/title-ix-bu-policies/
http://www.bu.edu/policies/employment/sexual-misconducttitle-ix-policy/

All faculty, Postdoctoral Research Associates, Ph.D. students, and graduate students with teaching responsibilities are “responsible employees” of BU, and as such are *mandatory reporters* of sexual misconduct or harassment if they hear of such behaviors, and must report them to Kim Randall, the Title IX Coordinator, or a Deputy Title IX Coordinator (see below). See the links above for a comprehensive list of definitions outlining which behaviors qualify. Due to our role as mandatory reporters, we cannot guarantee confidentiality if a student tells us about harassment or sexual misconduct.

Within CAS, mandatory reporting may also be made to the following CAS Deputy Title IX Coordinators:

* Danielle Kane, Deputy Title IX & DEI Outreach (Undergraduates)
dnkane[at]bu[dot]edu / (617) 353-2401

You may also file an [incident report](https://cm.maxient.com/reportingform.php?BostonUniv&layout_id=2) directory to the Equal Opportunity Office (EOO).

For confidential reporting of sexual misconduct or harassment, students have a number of resources available to them (listed in the links above), including the [Sexual Assault Response and Prevention Center (SARP)](https://www.bu.edu/shs/sarp/), (617) 353-7277, sarp[at]bu[dot]edu; [Student Health Services (SHS)](https://www.bu.edu/shs/), and the [University Chaplains](https://www.bu.edu/chapel/about/staff/chaplains/).

You may also contact the National: [National Sexual Assault Hotline](https://rainn.org/get-help/national-sexual-assault-hotline/), which provides confidential, one-on-one, crisis support 24/7 at (800) 656-4673.

### What happens after a report is made

Reporting to any of the listed options above (except SARP or the NSAH) will result in disclosure to the BU Title IX office, who will work together alongside the individual who was harmed to determine a course of action. It is important to note again that all BU staff and employees are mandatory reporters to Title IX. This means they are required to report anything they experience, see, or hear about to BU’s Title IX office. The next step in the BU Title IX office process is that an investigator from their office will conduct outreach to the target of the inappropriate behavior, which includes providing resources for support. They will then ask this individual if they want the office to move forward with an investigation. The target is in control of the process at this point. If they do not want an investigation to move forward, it will not. 

The only way that an investigation will move forward without the support of the targeted individual is if: 

1)	The incident was part of a larger pattern at BU (one example is if multiple individuals reported the same person for comments that constituted sexual harassment or discrimination); 
2)	The accused individual has a history of violence, sexual violence, arrest, or the incident was committed by multiple perpetrators; 
3)	The incident was perpetrated with a weapon, included physical violence (such as hitting, restraint, pushing, or kicking), or the threat of violence; 
4)	The affected individual is a minor; 
In the event of an investigation, if the individual causing harm is from an institution other than BU, the BU Title IX office will coordinate with the Title IX office at the individual’s home institution.
The target will always be included and informed of the results of their disclosure, any action that is taken, and the results of an investigation. 

### What to do if someone discloses to you (and you are not a mandatory reporter) 

If a friend in the SMAGL discloses that they have been targeted by sexual misconduct, there are a number of ways in which you can support them: 

*	Tell them that you believe them, that you support them, that it is not their fault, that no one deserves to be targeted by such behavior. 
*	Provide them with the list of contact information and resources included in this document. 
*	Ask if they want your help in finding out what their options are. 
*	Ask what else you can do to help. 
*	Respect their decision not to talk with you if they don’t want to. 

It is common for survivors of sexual assault not to initially name what happened to them as rape or abuse although they may recognize harmful behavior. Over time, as they feel safer, they may try to understand the experience through talking about it. The support of a friend can be extremely beneficial in the healing process. 

Remember that the well-being of the person who was harmed must be prioritized. Reporting an incident to police or others without the support or knowledge of the person who was harmed could be more traumatic than helpful.

### What to do if you have been sexually assaulted, or targeted by sexual misconduct 

We support you. You have the right to: 

*	Talk to anyone about your experience; 
*	To *not* talk to anyone about your experience (silence can make the healing process more difficult, and we encourage you to reach out to a trusted friend or one of the BU resources listed above);
*	Change your mind about talking to anyone about your experience at any time; 
*	Report to your PI, the police, or any of the other reporting options listed above; 
*	Bring someone with you to provide support during reporting or any resulting discussions; 
*	To seek reasonable accommodations to minimize the impact of the experience on the success of your work in the SMAGL; 
*	To seek medical assistance, including medical care and a medical forensic exam (keep in mind that a forensic exam is a time-limited intervention that could help in court - in MA the limit for an exam to be effective is 120 hours from the event). 

This is not intended to be a comprehensive list. 

## What to do if you see something inappropriate 

The most effective way we can prevent harm to any member of our community is by looking out for each other. All SMAGL community members are expected to share in the responsibility of creating a safe environment and to act when they witness behavior that could be harmful to others. In any potentially harmful situation there are often other individuals along the way who recognize there is a problem and have the ability to step in and help the targeted individual. 

Bystander intervention training programs provide tools to help bystanders act effectively in the way that works best for them. Active bystanders are individuals who take the responsibility to act when they see something or hear something that makes them uncomfortable. You do not need training in order to be an active bystander. 

Here are some suggestions to take an active role in the safety of our community: 

*	Be aware of your surroundings and social situations. 
*	If a situation makes you or others uncomfortable, or it looks like someone is being targeted, recognize that this is a problem and that you can be part of the solution to help. 
*	Take action to diffuse the situation while staying safe; some ideas include checking in with the targeted individual, telling a PI or PRA what is happening, recruiting help from friends, diffusing the situation by distracting those involved (look at that neat thing over there!).
*	If you are uncertain if there is a problem, check in with the individuals involved to see if they are okay or need help. 

Look out for your friends and lab mates, but never put yourself at risk! 

## The special case of field-based harassment

A big question SMAGL folks have is what to do if harassment happens in the field. The field is a complicated situation where we are doing university-sponsored research or work, but are not actually on university property, making the university's responsibility/liability for addressing harassment in such situtation ambiguous and often case-specific. 

Generally, Title IX responsibilities for the university are restricted to harassment of BU-affiliated people by other BU-affiliates or BU-sponsored entities. This means that if you are harassed by someone off BU property, by someone not affiliated with BU, it is generally not considered a Title IX violation. Having said that, if you are experiencing harassment while conducting BU-sponsored fieldwork, BU will do their best to help you to get out of that situation.

If you experience or witness harassment while in the field conducting research with the SMAGL, here is what we recommend:

* If possible, find a conficante in the field who you can trust who is not a mandatory reporter. Being able to talk through harassment with someone in person is crucial.
* Assess the situation - is the harassment coming from a BU affiliate (i.e., someone being paid by the university or with a formal affiliation with the university)? If so, disclosure of this to your PI or field manager (typically a PRA or Ph.D. student) may trigger a mandatory report. If you don't want an investigation to be triggered, please contact SARP (if you have a WiFi connection, you can call phone numbers internationally for a very low price using [Skype](https://www.skype.com/en/)) to get advice on how to proceed.
* If the harassment is *not* coming from a BU affiliate (and/or if you've contacted SARP and they tell you that this is not something that will trigger a mandatory report), please send your PI (likely Prof. Schmitt) a message via WhatsApp or Slack saying "I would like to speak over the phone as soon as possible about something happening at the field site". Please use those words exactly. I will arrange a call as soon as possible. On the call, I will remind you about the mandatory reporting requirements and encourage you to assess, again. Together, we will re-assess the situation and work together to plan a way to remediate. If, in discussion, we decide that this is something we want to formally report and act on, we will work together to put it in writing in a way that will result in the outcome that you prefer.
* **Consequences for the harasser**: If the person's behavior violates this Code of Conduct, or any of the regulations outlined above, they will face consequences. Those consequences depend on the behavior and how pervasive or severe it may have been, and may range from a discussion with the PI in an attempt to end the offending behavior, separation of individuals to other aspects of projects until a solution can be reached, to complete dismissal from the project. Please keep in mind that these individuals may be embedded in local communities, and so such interventions may require discussions with local collaborating entities and communities in order to figure out a solution. Please also keep in mind that these communities and local entities may have their own policies and legal requirements that must be followed if a formal complaint is filed.
* **Consequences for the harassed**: We will work with SMAGL members experiencing harassment in the field (that is not reportable to Title IX; remember, reportable harassment will be investigated and likely managed by the university) to come to the best possible outcome for that individual. This may range from dismissal of a harasser from fieldwork/sites, a pause in field collections to address the issue, a change in field sites (for the harasser or the person harassed), or an emergency flight home from the field (this is not an exhaustive list). Our goal is to ensure that an individuals research not be severely disrupted by our own addressing of these issues, so as not to exacerbate the disruptions already likely caused by the harassment, but this will also depend on the desires of the harassed with respect to their research.


#
#
#
#
#
#
#
#
#
#

***

# [**Back to the Guide**](https://fuzzyatelin.github.io/smagl_student_guide/overview.html)

***
# [**SMAGL *Undergraduate* Student Resources**](https://fuzzyatelin.github.io/smagl_student_guide/smagl_ugrad.html)
***
# [**SMAGL *Graduate* Student Resources**](https://fuzzyatelin.github.io/smagl_student_guide/smagl_grad.html)
***