---
title: "SMAGL Schmitt Lab Field Sites and Experiences"
author: "Christopher A Schmitt</br>Boston University"
date: "August 15, 2026"
output: 
  rmdformats::readthedown:
    toc_depth: 5
---

The Schmitt Lab has three major field-based projects that each focus on different elements of how wild primates adapt to ecological extremes: one is focused on the conservation genetics and adaptations to high elevations of Critically Endangered yellow-tailed woolly monkeys (*Lagothrix flavicauda*), at times in comparison to lowland Peruvian woolly monkeys (*Lagothrix lagotricha tschudii*) in **Perú** (current lab members working on this project include Pain, Rojas, Finnerty, Corn, Bronstein, and Ndukwe); one focuses on various metabolic adaptations and evolutionary/population genomics in wild savanna monkeys (*Chlorocebus* spp.), with a specific emphasis on vervet monkeys (*Chlorocebus pygerythrus*) in **South Africa** (current lab members working on this project include Martin, Erkens, Mao, Kim, and Zhang); and one focuses on genomic and physiological adaptations to high elevations and cold in wild Himalayan langurs (*Semnopithecus schistaceus*) in the Mandal Valley in Uttarakhand, **India** (current lab members working on this project include Ghorui). Each project has different emphases, and each has multiple associated field sites that are potentially open to student research.

***

## Perú

***

Although our research in Perú focuses on yellow-tailed woolly monkeys at the El Toro field site in Distrito Yambrasbamba, Región Amazonas, there are several other Peruvian field sites that are open to Schmitt Lab students, each with a unique suite of available primate species to study across a range of ecological and anthropogenic conditions. 

We access these sites primarily though several collaborative groups, which means that working at these sites comes with the expectation of continued collaboration with these groups (noted below). Undergraduate and Graduate students interested in working at these field sites should keep in mind that community priorities may need to guide potential research project objectives, and that the endangered status of many of these primates may impose constraints against more invasive research methods.

We also work with experienced field guides Elvis Charpentier and Adriano Soto Fluker to safely conduct biological survey work outside of established field sites.

### El Toro, Distrito Yambrasmamba, Región Amazonas

### Beirut, Distrito Corosha, Región Amazonas

### Cocha Cashu Biological Station

### Wildlife Conservation Lab at Los Amigos Biological Station

### Reserva Nacional de Tumbes

### Huiquilla, Amazonas

***

## South Africa

***

Our research in South Africa dates back to before the establishment of the SMAGL, and is an extension of the **Vervet Phenome/Genome Project**, part of the **International Vervet Research Consortium**.

### Faculty of Microbiology, North West University, Potchefstroom (North West)

In Potchefstroom, we conduct research in a state-of-the-art genomics lab at North-West University in collaboration with [Ms. Prudent Mokgokong](https://natural-sciences.nwu.ac.za/unit-environmental-sciences-and-management/prudent-mokgokong) of the Faculty of Microbiology. Potch is a relatively safe, small college town about two hours south of Johannesburg, where Schmitt Lab members typically lodge in local short-term rentals or in the lovely NWU Sports Village complex. Although our work in Potch focuses primarily on wet bench work in Prudent's lab, we also occasionally collect data on the urban vervet monkeys that can be seen on campus feasting from the garbage bins.

### Soetdoring Nature Reserve, Free State

Soetdoring Nature Reserve occupies 6173 Ha of highveld grassland, including the Modder River and the Krugersdrift Dam. We study three vervet groups (Group 1, Group 2, and Group 3) here that remain on the south side of the Modder River, primarily occupying riparian forest and adjacent *Vachellia* thornveld near the eastern entrance to the reserve. These vervets almost exclusively subsist on natural forage, with occasional food scraps left by visitors. Although the reserve itself is a mixture of grassland and Nama Karoo biomes, the landscape surrounding the reserve consists almost entirely of large-scale agricultural fields consisting of maize, wheat, alfalfa, and sunflower cultivation. Commonly seen game on the Reserve include zebra, eland, ostrich, hartebeest, wildebeest, impala, waterbuck, blesbok, springbok, and the occasional aardvark (there are no predators larger than a jackal). Schmitt Lab researchers working in Soetdoring live in nearby Soutpan with long-time project friends Liza and Krona (who run the Turksvy Koffiewinkel and associated lodgings, and make excellent melkoffie), a ~30 minute drive from the reserve.

### Southford Stud Horse Farm, Northern Cape

The Southford Stud Horse Farm is one of the longest-running stud farms in South Africa, breeding thoroughbreds on a farm running along the southern bank of the Orange River in Northern Cape near the Gariep Dam. Between the high-calorie horse feed and mixed agriculture including pecanuts and maize, it's also got a large vervet monkey population that appears able to weather difficult environmental conditions (like cold and drought), but is susceptible to greater human-mediated threats like electrocution from power lines, loss of limb from snares, and being shot at by local farmers. We've worked (and stayed) with farm owner David Southey since 2010 to study how living on the farm has influenced the biology and well-being of the Southford Study monkeys.

### Vervet Research Colony, Wake Forest School of Medicine, North Carolina

The Vervet Research Colony (VRC) is the only NIH-funded biomedical research resource for US-born vervets (also known as African green monkeys, AGMs, or *Chlorocebus sabaeus*). The VRC serves a wide range of local, regional and national investigators by providing animals, biological samples, data, consultation and training pertaining to the use of this species as multi-categorical, translational models of human disease. All of the animals in the colony are captive-born and mother-reared in species-typical social groups.

The Schmitt Lab primarily collaborates with the VRC through [Dr. Matthew Jorgensen](https://school.wakehealth.edu/faculty/j/matthew-j-jorgensen), [Dr. Kylie Kavanagh](https://school.wakehealth.edu/research/labs/kylie-kavanagh-lab), and [Dr. Ellen Quillen](https://school.wakehealth.edu/faculty/q/ellen-quillen) on research related to the genomics underlying growth, metabolic disorder and obesity. 

***

## India

***

The most recent field site made available to the SMAGL was brought to us by Ph.D. student Soumalya Ghorui, in his role as part of the [Himalayan Langur Project](https://himalayanlangur.com). Founded in 2014 by [Dr. Himani Nautiyal](https://www.himaninautiyal.com/), the Himalayan Langur Project began as a focused field study on the ecology and diet of the Central Himalayan langur (*Semnopithecus schistaceus*) in Mandal Valley, Uttarakhand. Early work centered on habituation and behavioral observation, laying the foundation for long-term research on primate ecology in human-dominated landscapes. Since then, the project has expanded into a multidisciplinary research program integrating behavioral ecology, evolutionary biology, and human–wildlife interactions.

You can learn more about the field site and the research conducted there at the [Himalayan Langur Project's excellent website](https://himalayanlangur.com).


#
#
#
#
#
#
#
#
#
#

***

# [**Back to the Guide**](https://fuzzyatelin.github.io/smagl_student_guide/overview.html)

***
# [**SMAGL *Undergraduate* Student Resources**](https://fuzzyatelin.github.io/smagl_student_guide/smagl_ugrad.html)
***
# [**SMAGL *Graduate* Student Resources**](https://fuzzyatelin.github.io/smagl_student_guide/smagl_grad.html)
***