---
title: "AN333/733: Final Projects"
author: "Christopher A Schmitt"
date: "December 4, 2018"
output: html_document
---

##Final Projects for AN333/733

Your final project is a critically important part of this course. Once you’ve learned population genetic methods and how to use them on human *UCP1* data, it’s time to choose a candidate gene of your own to analyze!

Choose a gene that you can show is related to a trait that is integral to why you are interested in human population and evolutionary history. You will establish hypotheses, based on your knowledge of human population and evolutionary history, regarding how that gene should vary across the *1000 Genomes Project* dataset, and then test your hypotheses using the analytical methods learned in class.

We will choose loci together as part of [Lab 7](https://fuzzyatelin.github.io/AN333_Fall18/Lab7-newlocus.html), but this guide is to help you through the process of preparing an writing your final paper.

##Final Project Paper Formatting

Final papers will have formatting similar to a paper submitted to the [*American Journal of Physical Anthropology*](https://onlinelibrary.wiley.com/journal/10968644). This will include:

1)  **Title and Author List**: Your title should be short and describe the central idea of your paper. See other titles published in the *AJPA* for some helpful examples. All projects should be *single authored*!

2)	**Abstract**: Please provide an abstract of 250 words or fewer containing the major keywords summarizing the article, structured with the following headings in bold, separated by line breaks: *Objectives*, *Materials and Methods*, *Results*, *Discussion*.

3)	**Introduction**: The *Introduction* should provide enough background for the reader to understand the objectives and motivation of the study. Extensive literature review is unnecessary and should be avoided.

4)	**Materials and Methods**: This section should include all the information that would be necessary for a replication of the study as well as for a generally informed reader to evaluate the study and its results. Highly specialized procedures or forms of analysis may need explication so as to be understood by a generalist. A clear statement of approval by relevant ethics panels must be included for your dataset (see original publication of the *1000 Genomes Project* Consortium to find their ethics statement).

5)	**Results**: The *Results* section should present the findings of the study without excessive interpretation.

6)	**Discussion**: The *Discussion* section is the appropriate place for all interpretation of the study results, comparison with the results of previous studies, conclusions and hypotheses based on those comparisons, and suggestions for future research. No new analyses or results should appear in this section. Interpretations and conclusions should be restrained and justified by the results.

7)	**References**: For the *References section*, we’ll follow AAPA guidelines:

>As of 2017, the references of the journal should be prepared according to the [Publication Manual of the American Psychological Association (APA) (6th edition)](https://www.apastyle.org/). This means in text citations should follow the author-date method whereby the author's last name and the year of publication for the source should appear in the text, for example, (Jones, 1998). Use of et al. is determined by the number of authors and whether it is the first time a reference has been cited in the paper. Specifically, articles with one or two authors include all names in every in-text citation; articles with three, four, or five authors include all names in the first in-text citation but are abbreviated to the first author name plus et al. upon subsequent citations; and articles with six or more authors are abbreviated to the first author name plus et al. for all in-text citations.
>
>The complete reference list should appear alphabetically by name at the end of the paper. Please note that for journal articles, issue numbers are not included unless each issue in the volume begins with page 1, and a DOI should be provided for all references where available. For more information about APA referencing style, please refer to the APA FAQ.
>
>Reference examples follow:
>
>Journal:
>Scruton, R. (1996). The eclipse of listening.The New Criterion, 15(3), 5-13.
>
>Book:
>Calfee, R. C., & Valencia, R. R. (1991). APA guide to preparing manuscripts for journal publication.Washington, DC: American Psychological Association.

8)  **Tables and Figures**: The best way to represent your data may be in a figure or table (for example, an image of the linkage blocks in your gene of interest, or of a neighbor-joining tree, or a table summarizing relavant neutrality statistics with their p-values). If you plan to include tables and figures, please number them in the order they appear in the text (Figure 1, Figure 2, etc; Table 1, Table 2, etc) with a descriptive caption describing/explaining what the table or figure is meant to show us that is relevant to your hypotheses (e.g., "Figure 1: Linkage block of the gene *ESPN3*, notice that there is high linkage between SNP of interest rs31459 and SNP rs44444, which is a candidate gene for obesity").

<ul><li>For guidance on how to include and caption a **figure** in a Google Doc, please [see this helpful guide](https://docs.google.com/document/d/1HYgCxV7noTwBJ70uh7uSHtmUfUSzoI5A5XWunWgRVaU/edit).</li>

<li>For guidance on how to add and edit a **table** in a Google Doc, please [see this helpful guide](https://support.google.com/docs/answer/1696711?co=GENIE.Platform%3DDesktop&hl=en).</li></ul>

To see an example article written by your professor in the *American Journal of Physical Anthropology*, check out this citation (written in APA format):

[Turner, T.R., Schmitt, C.A., Cramer, J.D., Lorenz, J., Grobler, J.P., Jolly, C.J., & Freimer, N.B. (2018). Morphological variation in the genus *Chlorocebus*: Ecogeographic and anthropogenically mediated variation in body mass, postcranial morphology, and growth. *Am J Phys Anthropol* 166(3), 682-707.](https://onlinelibrary.wiley.com/doi/full/10.1002/ajpa.23459)

<center>
###[**Please submit your Final Project paper as a single saved Google Doc file (downloaded as a Microsoft Word, or *.docx* file) at this link by 5:00pm of Monday, December 17**](https://goo.gl/forms/3WFuWsI9A2jHeE123)
</center>
<br>
<br>
<br>


